import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from 'next/font/google';
import "./globals.css";
import Header from "@/components/public/Header";
import Footer from "@/components/public/Footer";
import { RouteLoadingIndicator } from '@/components/public/signup/RouteLoadingIndicator'
import { Suspense } from 'react';
import { ErrorBoundary } from '@/components/public/ErrorBoundary';
import { Toaster } from "@/components/ui/use-toast"

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <ErrorBoundary>
          <Suspense fallback={<RouteLoadingIndicator />}>
              <Header />
              <main className="flex-grow">
                {children}
              </main>
              <Footer />
          </Suspense>
        </ErrorBoundary>
        <Toaster />
      </body>
    </html>
  );
}
